
[GHEGist]
  Public = false
  access_token = ""
  auto_sync = false
  base_url = ""
  file_name = ""
  gist_id = ""
  upload_url = ""

[General]
  Backend = "gist"
  Cmd = []
  Color = true
  Column = 40
  Editor = "nvim"
  Format = "$description: $command $tags"
  SelectCmd = "fzf --layout=reverse --border --height=20% --min-height=10 --cycle --prompt=Snippets:"
  SnippetDirs = []
  SnippetFile = "$XDG_CONFIG_HOME/pet/snippet.toml"
  SortBy = ""

[Gist]
  Public = false
  access_token = ""
  auto_sync = false
  file_name = "pet-snippet.toml"
  gist_id = ""

[GitLab]
  ID = ""
  Url = ""
  Visibility = "private"
  access_token = ""
  auto_sync = false
  file_name = "pet-snippet.toml"
  skip_ssl = false
